apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-workflows-server-tls
  namespace: argo-workflows
spec:
  dnsNames:
    - argo-workflows.arffornia.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: default-issuer
  secretName: argo-workflows-server-tls