apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
  - workflows/
  - namespace.yaml
  - argo-workflows-server-certificate.yaml
  - github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.7.6
  - ingress.yaml
  - sa.yaml

patches:
  - path: argo-workflows-server-patch.yaml 