apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-executor
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-executor-role
  namespace: argo-workflows
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflowtaskresults
    verbs:
    - create
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-executor-role-binding
  namespace: argo-workflows
subjects:
  - kind: ServiceAccount
    name: argo-workflows-executor
    namespace: argo-workflows
roleRef:
  kind: Role
  name: argo-workflows-executor-role
  apiGroup: rbac.authorization.k8s.io