apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-bot-json-config
  namespace: argo-workflows
data:
  config.js: |
    module.exports = {
      repositories: [
        'TheGostsniperfr/infra',
      ]
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-bot-configmap
  namespace: argo-workflows
data:
  RENOVATE_PLATFORM: "github"
  RENOVATE_ENDPOINT: "https://github.com/thegostsniperfr"
  RENOVATE_GIT_FS: "http"
  # RENOVATE_USERNAME: ""
  # RENOVATE_PASSWORD: ""
  LOG_LEVEL: "debug"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
