apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: renovate-credentials-secret
  namespace: argo-workflows
spec:
  vaultRole: renovate-role
  path: kvv2/argo-workflows/renovate/credentials
  type: Opaque
  keys:
    - RENOVATE_USERNAME
    - RENOVATE_PASSWORD