apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: adminer-basic-auth-secret
  namespace: adminer
spec:
  path: kvv2/adminer/basic-auth
  vaultRole: adminer-role
  keys:
    - auth
  type: Opaque
