apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: smb-nas-credentials
  namespace: default
spec:
  path: kvv2/smb/nas-credentials
  vaultRole: csi-driver-smb-role
  keys:
    - username
    - password
  type: Opaque
