apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgres-s3-credentials
  namespace: postgres
spec:
  path: "kvv2/minio-s3/credentials"
  vaultRole: postgres-role
  keys:
    - rootUser
    - rootPassword
  templates:
    AWS_ACCESS_KEY_ID: "{% .Secrets.rootUser %}"
    AWS_SECRET_ACCESS_KEY: "{% .Secrets.rootPassword %}"
  type: Opaque
