apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-credentials
  namespace: minio-s3
spec:
  path: kvv2/minio-s3/credentials
  vaultRole: minio-s3-role

  keys:
    - rootUser
    - rootPassword

  type: Opaque
