apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  path: kvv2/grafana/admin
  vaultRole: monitoring-role
  keys:
    - admin-user
    - admin-password
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: alertmanager-discord-secret
  namespace: monitoring
spec:
  path: kvv2/monitoring/discord
  vaultRole: monitoring-role
  keys:
    - webhook_general
    - webhook_critical
    - webhook_arffornia
  type: Opaque
