apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
spec:
  path: kvv2/grafana/admin
  vaultRole: monitoring-role
  keys:
    - admin-user
    - admin-password
  type: Opaque
