apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  path: kvv2/cert-manager/cloudflare-api-token
  vaultRole: cert-manager-role
  keys:
    - api-token
  type: Opaque
