apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder

resources:
  - namespace.yaml
  - secret.yaml
  - certificate.yaml

helmCharts:
  - name: coder
    repo: https://helm.coder.com/v2
    version: 2.30.0
    releaseName: coder
    namespace: coder
    valuesFile: values.yaml
