apiVersion: v1
kind: ConfigMap
metadata:
  name: bluemap-nginx-config
  namespace: arffornia-bluemap-web
data:
  default.conf: |
    server {
        listen 8080;
        server_name map.arffornia.com;

        root /data/bluemap-web;
        gzip_static on;

        location /maps/ {
            gzip_static always;

            location ~* ^/maps/[^/]*/tiles/ {
                error_page 404 = @empty;
            }

            location ~* ^/maps/[^/]*/live/ {
                proxy_pass http://arffornia-server-arcane-minecraft-bluemap-live.arffornia-server-arcane.svc.cluster.local:8100;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }

        location @empty {
            return 204;
        }

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.json$ {
            default_type application/json;
        }
    }