apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  labels:
    app: coder
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  project: default
  source:
    repoURL: https://github.com/TheGostsniperfr/infra.git
    targetRevision: HEAD
    path: k8s/config/coder
  destination:
    name: in-cluster
    namespace: coder
