apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: plex
spec:
  secretName: plex-tls
  dnsNames:
    - plex.arffornia.com
  issuerRef:
    name: default-issuer
    kind: ClusterIssuer
    group: cert-manager.io