apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plex

resources:
  - namespace.yaml
  - pvc.yaml
  - certificate.yaml
  - secret.yaml

helmCharts:
  - name: plex-media-server
    repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    version: "1.2.0"
    releaseName: plex
    namespace: plex
    valuesFile: values.yaml