# Default values: https://github.com/plexinc/pms-docker/blob/master/charts/plex-media-server/values.yaml
# Doc: https://www.plex.tv/blog/plex-pro-week-23-a-z-on-k8s-for-plex-media-server/

image:
  # -- The public dockerhub registry
  registry: index.docker.io
  repository: plexinc/pms-docker
  # renovate: datasource=custom.plex depName=plex versioning=loose
  tag: "1.42.2.10156-f737b826c"
  sha: ""
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  ingressClassName: "public"
  annotations:
    cert-manager.io/cluster-issuer: default-issuer

  url: "plex.arffornia.com"

  tls:
    - secretName: plex-tls
      hosts:
        - plex.arffornia.com

pms:
  # Get token: https://www.plex.tv/claim/
  claimSecret:
    name: "plex-claim-secret"
    key: "token"

  config:
    existingClaim: "plex-config-pvc"

  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "256Mi"
      cpu: "250m"

service:
  type: ClusterIP

extraVolumes:
  - name: media
    persistentVolumeClaim:
      claimName: plex-nas-pvc

extraVolumeMounts:
  - name: media
    mountPath: /data/media
